@startuml
skinparam activity {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
!pragma useVerticalIf on
start
title Activity Diagram for AppConfig

if (xmlValidator) then (yes)
:xmlValidator;
endif
if (restTemplate) then (yes)
:restTemplate;
endif
stop
@enduml
