@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.processor.CodeMetricsGenerator
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class CodeMetricsGenerator {
 - org.slf4j.Logger logger
 + void () generateMetrics()
 + java.math.BigDecimal (float) roundDef()
 + java.math.BigDecimal (float, int) roundDecimals()
 + java.lang.String (java.lang.String) loadTemplate()
 + int (java.io.File) countLinesOfCode()
 + int (java.io.File) countMethodsInClass()
}
@enduml