@startuml
skinparam usecase {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
left to right direction
title Use-Case Diagram for DropboxAuthStateCleanupJob

actor User
usecase "cleanupExpiredStates" as UC_cleanupExpiredStates
User --> UC_cleanupExpiredStates
@enduml