@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.utils.GCPSecretManagerUtil
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class GCPSecretManagerUtil {
 - org.slf4j.Logger logger
 + java.lang.String (java.lang.String, java.lang.String, java.lang.String) getSecret()
 + java.lang.String (java.lang.String) getSecret()
}
@enduml