@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.entity.Handover
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class Handover {
 - java.lang.Integer id
 - org.apache.clusterbr.zupportl5.entity.Incident incidentID
 - org.apache.clusterbr.zupportl5.entity.Engineer fromEngineerID
 - org.apache.clusterbr.zupportl5.entity.Engineer toEngineerID
 - java.sql.Timestamp handoverTime
 - java.lang.String notes
 + java.lang.Integer () getId()
 + void (java.lang.Integer) setId()
 + org.apache.clusterbr.zupportl5.entity.Incident () getIncidentID()
 + void (org.apache.clusterbr.zupportl5.entity.Incident) setIncidentID()
 + org.apache.clusterbr.zupportl5.entity.Engineer () getFromEngineerID()
 + void (org.apache.clusterbr.zupportl5.entity.Engineer) setFromEngineerID()
 + org.apache.clusterbr.zupportl5.entity.Engineer () getToEngineerID()
 + void (org.apache.clusterbr.zupportl5.entity.Engineer) setToEngineerID()
 + java.sql.Timestamp () getHandoverTime()
 + void (java.sql.Timestamp) setHandoverTime()
 + java.lang.String () getNotes()
 + void (java.lang.String) setNotes()
}
@enduml