@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.repository.HandoverRepository
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class HandoverRepository {
}
HandoverRepository ..|> orgspringframeworkdatajparepositoryJpaRepository
HandoverRepository ..|> orgspringframeworkdatarepositoryListCrudRepository
HandoverRepository ..|> orgspringframeworkdatarepositoryListPagingAndSortingRepository
HandoverRepository ..|> orgspringframeworkdatarepositoryqueryQueryByExampleExecutor
HandoverRepository ..|> orgspringframeworkdatarepositoryCrudRepository
HandoverRepository ..|> orgspringframeworkdatarepositoryPagingAndSortingRepository
HandoverRepository ..|> orgspringframeworkdatarepositoryRepository
@enduml