@startuml
skinparam activity {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
!pragma useVerticalIf on
start
title Activity Diagram for HandoverController

if (createHandover) then (yes)
:createHandover;
endif
if (getAll) then (yes)
:getAll;
endif
if (getById) then (yes)
:getById;
endif
if (update) then (yes)
:update;
endif
if (delete) then (yes)
:delete;
endif
if (lambdaupdate3) then (yes)
:lambdaupdate3;
else (nothing)
:No Operation;
endif
if (lambdaupdate2) then (yes)
:lambdaupdate2;
else (nothing)
:No Operation;
endif
if (lambdagetById1) then (yes)
:lambdagetById1;
else (nothing)
:No Operation;
endif
if (lambdagetById0) then (yes)
:lambdagetById0;
else (nothing)
:No Operation;
endif
stop
@enduml
