@startuml
skinparam usecase {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
left to right direction
title Use-Case Diagram for HandoverService

actor User
usecase "findAll" as UC_findAll
User --> UC_findAll
usecase "findById" as UC_findById
User --> UC_findById
usecase "save" as UC_save
User --> UC_save
usecase "update" as UC_update
User --> UC_update
usecase "deleteById" as UC_deleteById
User --> UC_deleteById
@enduml