@startuml
skinparam usecase {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
left to right direction
title Use-Case Diagram for HtmlSwaggerDocGenerator

actor User
usecase "generateSwaggerDocs" as UC_generateSwaggerDocs
User --> UC_generateSwaggerDocs
@enduml