@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.repository.IncidentlogsRepository
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class IncidentlogsRepository {
}
IncidentlogsRepository ..|> orgspringframeworkdatajparepositoryJpaRepository
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryListCrudRepository
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryListPagingAndSortingRepository
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryqueryQueryByExampleExecutor
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryCrudRepository
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryPagingAndSortingRepository
IncidentlogsRepository ..|> orgspringframeworkdatarepositoryRepository
@enduml