@startuml
skinparam activity {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
!pragma useVerticalIf on
start
title Activity Diagram for IncidentService

if (findAll) then (yes)
:findAll;
endif
if (getById) then (yes)
:getById;
endif
if (save) then (yes)
:save;
endif
if (update) then (yes)
:update;
endif
if (deleteById) then (yes)
:deleteById;
endif
if (getByCriteria) then (yes)
:getByCriteria;
endif
if (getByCriteriaWithCriteriaAPI) then (yes)
:getByCriteriaWithCriteriaAPI;
endif
if (lambdaupdate0) then (yes)
:lambdaupdate0;
else (nothing)
:No Operation;
endif
stop
@enduml
