@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.repository.KnowledgebaseRepository
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class KnowledgebaseRepository {
}
KnowledgebaseRepository ..|> orgspringframeworkdatajparepositoryJpaRepository
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryListCrudRepository
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryListPagingAndSortingRepository
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryqueryQueryByExampleExecutor
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryCrudRepository
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryPagingAndSortingRepository
KnowledgebaseRepository ..|> orgspringframeworkdatarepositoryRepository
@enduml