@startuml
skinparam sequence {
 ArrowColor #4D7A97 
 ParticipantBorderColor #4D7A97 
 ParticipantBackgroundColor #DEE3E9 
}
title Sequence Diagram for MessageService

actor User
User -> MessageService: getMessage()
participant String
MessageService -> String: invoke dependency
participant Object
MessageService -> Object: invoke dependency
participant Locale
MessageService -> Locale: invoke dependency
MessageService --> User : return
User -> MessageService: getMessage()
MessageService -> String: invoke dependency
MessageService --> User : return
User -> MessageService: getMessageDefault()
MessageService -> String: invoke dependency
MessageService --> User : return
@enduml