@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.dto.MethodResultXml
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class MethodResultXml {
 - T result
 - java.lang.Boolean success
 - java.lang.String message
 + T () getResult()
 + void (T) setResult()
 + java.lang.Boolean () isSuccess()
 + void (java.lang.Boolean) setSuccess()
 + java.lang.String () getMessage()
 + void (java.lang.String) setMessage()
 + java.lang.String () toString()
}
MethodResultXml ..|> javaioSerializable
@enduml