@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.processor.OpenApiDocGeneratorBase
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class OpenApiDocGeneratorBase {
 - org.slf4j.Logger logger
 + java.util.List<java.lang.Class<?>> (java.lang.String) getClassesInPackage()
 + boolean (java.lang.reflect.Method) isHttpMethodAnnotatedWithHttpVerb()
 + java.lang.String (java.lang.reflect.Method) getHttpVerbFromMethod()
 + java.lang.String (java.lang.reflect.Method) getPathFromMethod()
 + java.lang.String (java.lang.String) loadTemplate()
 + java.lang.String (java.lang.String) removeTrailingSlash()
}
@enduml