@startuml
skinparam activity {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
!pragma useVerticalIf on
start
title Activity Diagram for PerformanceMetricController

if (getAll) then (yes)
:getAll;
endif
if (getById) then (yes)
:getById;
endif
if (create) then (yes)
:create;
endif
if (update) then (yes)
:update;
endif
if (delete) then (yes)
:delete;
endif
stop
@enduml
