@startuml
skinparam activity {
 BackgroundColor #DEE3E9 
 BorderColor #4D7A97 
 ArrowColor #4D7A97 
}
!pragma useVerticalIf on
start
title Activity Diagram for StaticContentController

if (root) then (yes)
:root;
endif
if (about) then (yes)
:about;
endif
stop
@enduml
