@startuml 
skinparam class { 
 BackgroundColor #DEE3E9 
 ArrowColor #4D7A97 
 BorderColor #4D7A97 
}
left to right direction 
title Class Diagram for org.apache.clusterbr.zupportl5.config.WebConfig
skinparam titleBackgroundColor White
skinparam classHeaderBackgroundColor #4D7A97 
skinparam stereotypeCBackgroundColor #F8981D 

class WebConfig {
 + void (org.springframework.web.servlet.config.annotation.InterceptorRegistry) addInterceptors()
 + void (org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry) addResourceHandlers()
 + void (org.springframework.web.servlet.config.annotation.ViewControllerRegistry) addViewControllers()
}
WebConfig ..|> orgspringframeworkwebservletconfigannotationWebMvcConfigurer
@enduml